[station]
name     = "Davis Vantage Pro 2"
latitude  = 50.174533   # decimal degrees, positive = North
longitude = 8.719422    # decimal degrees, positive = East
elevation = 167         # metres above sea level
timezone  = "Europe/Berlin"
